server:
  port: 8762
 
eureka:
  instance:
    hostname: eurekaserver2
    appname: eureka-cluster
  environment: local
  client:
    serviceUrl:
      defaultZone:
        http://eurekaserver2:8761/eureka
    registerWithEureka: true   #telling the server not to register himself in the service registry
    fetchRegistry: true
    
spring:
  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)
    